# Generated by Django 4.2.11 on 2026-02-27 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('historia_clinica', models.CharField(max_length=50, unique=True)),
                ('servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroGlucemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('algoritmo', models.IntegerField(default=1)),
                ('escalon', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='pacientes.paciente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
