# Generated by Django 5.2.1 on 2026-04-10 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicionGlucemia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("glicemia_actual", models.PositiveIntegerField()),
                ("glicemia_previa", models.PositiveIntegerField(blank=True, null=True)),
                ("infusion_activa", models.BooleanField(default=False)),
                ("hubo_ajuste_insulina", models.BooleanField(default=False)),
                (
                    "tercera_medicion",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio / Reinicio"),
                            ("seguimiento", "Seguimiento"),
                        ],
                        default="seguimiento",
                        max_length=20,
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=100)),
                ("subestado", models.CharField(blank=True, max_length=150)),
                (
                    "clase",
                    models.CharField(
                        choices=[
                            ("hipoglucemia", "Hipoglucemia"),
                            ("post_hipoglucemia", "Post-hipoglucemia"),
                            ("en_rango", "En rango"),
                            ("hiperglucemia", "Hiperglucemia"),
                            ("sin_clasificacion", "Sin clasificación"),
                        ],
                        default="sin_clasificacion",
                        max_length=30,
                    ),
                ),
                ("mensaje", models.TextField(blank=True)),
                ("conducta", models.TextField(blank=True)),
                ("proximo_control", models.CharField(blank=True, max_length=255)),
                ("observacion", models.CharField(blank=True, max_length=255)),
                ("tendencia", models.CharField(blank=True, max_length=50)),
                ("flecha_tendencia", models.CharField(blank=True, max_length=5)),
                ("delta", models.CharField(blank=True, max_length=20)),
                ("algoritmo_usado", models.CharField(blank=True, max_length=100)),
                ("velocidad_sugerida", models.CharField(blank=True, max_length=30)),
                ("bolo_ui", models.CharField(blank=True, max_length=30)),
                ("tasa_inicial_ui_h", models.CharField(blank=True, max_length=30)),
                ("tasa_algoritmo", models.CharField(blank=True, max_length=30)),
                ("requiere_recontrol", models.BooleanField(default=False)),
                ("suspender_insulina", models.BooleanField(default=False)),
                ("administrar_dextrosa", models.BooleanField(default=False)),
                ("reiniciar_insulina", models.BooleanField(default=False)),
                ("alerta_hgr", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mediciones_glucemia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición de glicemia",
                "verbose_name_plural": "Mediciones de glicemia",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
