# Generated by Django 5.2.1 on 2026-06-24 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitaWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(unpack_ipv4=True)),
                ("username_display", models.CharField(blank=True, max_length=150)),
                ("pagina", models.CharField(max_length=500)),
                ("metodo", models.CharField(default="GET", max_length=10)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("session_key", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("duracion_segundos", models.IntegerField(blank=True, null=True)),
                ("es_movil", models.BooleanField(default=False)),
                ("navegador", models.CharField(blank=True, max_length=100)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitas_web",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita web",
                "verbose_name_plural": "Visitas web",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="analytics_v_timesta_561461_idx"
                    ),
                    models.Index(fields=["ip"], name="analytics_v_ip_369b8b_idx"),
                    models.Index(
                        fields=["usuario"], name="analytics_v_usuario_8d6b24_idx"
                    ),
                ],
            },
        ),
    ]
