# Generated by Django 6.0.3 on 2026-03-13 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionGlucemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('glucemia', models.IntegerField()),
                ('modo', models.CharField(choices=[('inicio', 'Inicio / Reinicio (Algoritmo 1)'), ('alg2', 'Seguimiento - Algoritmo 2')], max_length=20)),
                ('infusion_activa', models.BooleanField(default=False)),
                ('glucemia_previa', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=30)),
                ('conducta', models.CharField(max_length=255)),
                ('mensaje', models.TextField(blank=True)),
                ('proximo_control', models.CharField(blank=True, max_length=255)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('tendencia', models.CharField(blank=True, max_length=50)),
                ('algoritmo_usado', models.CharField(blank=True, max_length=100)),
                ('velocidad_sugerida', models.CharField(blank=True, max_length=30)),
                ('bolo_ui', models.CharField(blank=True, max_length=30)),
                ('tasa_inicial_ui_h', models.CharField(blank=True, max_length=30)),
                ('alerta_hgr', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
