# Generated by Django 5.2.1 on 2026-04-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionglucemia',
            name='escalamiento_clinico',
            field=models.CharField(choices=[('normal', 'Normal'), ('persistente', 'Hiperglucemia persistente'), ('refractaria', 'Hiperglucemia refractaria')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='escalon_algoritmo',
            field=models.CharField(blank=True, help_text='Ej.: 120-149, 150-179, 180-209, >360, etc.', max_length=30),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='estable',
            field=models.BooleanField(default=False, help_text='Indica si el paciente permanece estable para espaciar controles.'),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='horas_desde_inicio',
            field=models.PositiveIntegerField(blank=True, help_text='Horas desde el inicio o reinicio de la insulinización EV.', null=True),
        ),
        migrations.AlterField(
            model_name='medicionglucemia',
            name='algoritmo_usado',
            field=models.CharField(blank=True, choices=[('', 'Sin algoritmo'), ('Algoritmo 1', 'Algoritmo 1'), ('Algoritmo 2', 'Algoritmo 2')], default='', max_length=20),
        ),
    ]
