# Generated by Django 6.0.3 on 2026-03-30 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicionglucemia',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Medición de glucemia', 'verbose_name_plural': 'Mediciones de glucemia'},
        ),
        migrations.RemoveField(
            model_name='medicionglucemia',
            name='glucemia',
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='administrar_dextrosa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='delta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='flecha_tendencia',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='glucemia_actual',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='hubo_ajuste_insulina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='reiniciar_insulina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='requiere_recontrol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='subestado',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='suspender_insulina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='tasa_algoritmo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='medicionglucemia',
            name='tercera_medicion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicionglucemia',
            name='clase',
            field=models.CharField(choices=[('hipoglucemia', 'Hipoglucemia'), ('post_hipoglucemia', 'Post-hipoglucemia'), ('en_rango', 'En rango'), ('hiperglucemia', 'Hiperglucemia'), ('sin_clasificacion', 'Sin clasificación')], default='sin_clasificacion', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicionglucemia',
            name='conducta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicionglucemia',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicionglucemia',
            name='glucemia_previa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicionglucemia',
            name='modo',
            field=models.CharField(choices=[('inicio', 'Inicio / Reinicio'), ('seguimiento', 'Seguimiento')], default='seguimiento', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicionglucemia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_glucemia', to=settings.AUTH_USER_MODEL),
        ),
    ]
